# Generated by Django 5.0.1 on 2024-01-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_answer_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numericdata',
            options={'verbose_name': 'Données'},
        ),
    ]
